name: Build
on: push

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.9
      uses: actions/setup-python@v1
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Build
      run: |
        python setup.py sdist
    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: jira-tracker.tar.gz
        path: dist/jira-tracker-*.tar.gz